### ISSUE TITLE
Removal of a Troll's birthday

### ISSUE THREAD

**Issue by Rosololol** [NoiTheCat/BirthdayBot#12]
I've had a troll in my discord and I am not able to remove their birthday, how can I do so?

**Comment by MitziMS13** [comment]
If that person is still in your server, you can remove their recorded Birthday with this command:
bb.override @trollnamehere remove

If that person is no longer in your server, there is no need to remove their birthday.  In order to announce, the bot must first give them the custom role -so if they are no longer there to receive the role then no happy birthday announcement will happen for that person.
