### ISSUE TITLE
Bot doesn't respond to messages that are replies

### ISSUE THREAD

**Issue by scytail** [NoiTheCat/BirthdayBot#14]
Birthday bot does not respond to any messages that are sent in the context of a reply, but functions correctly when not a reply. See the screenshot below:

![image](https://user-images.githubusercontent.com/9435256/140336781-c48816b1-dd8e-4729-b1d2-e6b804486348.png)

**Comment by NoiTheCat** [comment]
Hello, sorry for the very long delay in getting back to you!

At around the time you submitted this I had been waiting for a way to fix this on my end. Meanwhile though, Discord's policy changed to encourage bot interactions via slash commands instead of text commands. That policy will lead to the bot being unable to read text commands in the very near future, so I chose to focus on that instead of fixing the issue of responding to commands in non-standard messages and within threads.

Sorry again for the lack of communication and for not having done much with this issue in the meantime.

**Comment by scytail** [comment]
Thanks for the response! 
> That policy will lead to the bot being unable to read text commands in the very near future
Do you have a source for this? I maintain my own discord bot and hadn't heard anything about this.

**Comment by Ixrec** [comment]
I believe they're referring to https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-for-Verified-Bots Part of the reason this situation is confusing is that if your bot is in less than 75 servers, then it's not a "verified" bot and will not be affected.

Incidentally, I recently got my server to switch to BirthdayBot precisely because our existing bot for birthdays is unmaintained but widely used and verified bot, so we expect it to stop working in April 2022.

**Comment by NoiTheCat** [comment]
Yep that's correct, I should've elaborated a bit more. Large bots that can't justify the need to receive messages will lose the ability to do so in April. Small bots (under 75 servers) are completely unaffected, and if that's the case with yours you might still need to go into the application's page and turn on a switch to receive message intents regardless.
