### ISSUE TITLE
As of 12.01.2021, birthday announcements are not being posted

### ISSUE THREAD

**Issue by Metal12804xxButtercups** [NoiTheCat/BirthdayBot#15]
Worked great, but no december or january birthdays have posted. We have chacked to make sure they were properly set up with the bot, but the bot hasn't announced any birthdays for a while.

**Comment by MitziMS13** [comment]
Hello.  We apologize for the inconvenience, the bot did experience a malfunction back in November but has since been checked by Noi to prevent that from happening again.

Unfortunately, the birthdays will have to be re-entered manually either by the server members themselves or by you (or other bot admin) on their behalf with this command:
bb.override @member set mmm-dd

We also recommend you run this command as well:  bb.check which will alert you with ❌'s if any other bot configs need to be reset as well.
