### ISSUE TITLE
none of my members can set birthday

### ISSUE THREAD

**Issue by BabyRevan** [NoiTheCat/BirthdayBot#25]
None of my server members can set their birthday, I have to manually override them to their birth date, they're typing the command correctly and it's not saying birthday set or any reply, 
![image](https://user-images.githubusercontent.com/112896639/188495983-da80fbee-dc93-4165-8f00-ce8662625b08.png)

What command is for permissions for members to use the bot (not moderated ones)

**Comment by NoiTheCat** [comment]
Hi,
There is an issue in some servers where command permissions were improperly set some time ago but the issue has not shown itself until now. A few people have done this to successfully fix the issue:

1. From the user list on the side bar, click Birthday Bot to bring up its mini-profile
2. Click "Add to Server" (works even if the bot is already added)
3. Follow the prompts to authorize the bot

If this doesn't work, you can try kicking the bot. This is safe to do, as it won't delete any birthdays or existing settings unless the bot stays out of your server for long enough (months). You can then try the steps above, either finding the bot in another server or using its invite link. If you do take this option, keep in mind that you might at least need to bring its application role back to the right place in order to have it working properly again.

**Comment by NoiTheCat** [comment]
Given the frequency of this issue, I wrote up a small guide instructing users on how to possibly fix this issue:

https://noithecat.dev/bots/BirthdayBot/commandfix.html
