### ISSUE TITLE
BirthdayBot not announcing a birthday

### ISSUE THREAD

**Issue by maswartz** [NoiTheCat/BirthdayBot#43]
I was checking the bot's list and noticed today was a member of my server's birthday and the bot hadn't announced it. In their timezone it's already 11 PM so what up with that? For the record it just announced one last week so it does work.

**Comment by MitziMS13** [comment]
If the birthday person entered a time zone with the Birthday Bot, the announcement will post at midnight of that time zone as it overrides the server default time zone so that might be the issue.  But you can double check by posting this command to see if there are any errors being reported:  /config check

**Comment by maswartz** [comment]
> 

Not a valid setting.

**Comment by maswartz** [comment]
This is still happening. This time with my own.

**Comment by maswartz** [comment]
> If the birthday person entered a time zone with the Birthday Bot, the announcement will post at midnight of that time zone as it overrides the server default time zone so that might be the issue. But you can double check by posting this command to see if there are any errors being reported: /config check

Like I said two weeks ago this isn't a valid command.

**Comment by NoiTheCat** [comment]
Hello, this sounds like it may be a configuration issue. I suggest going to the support server in order to get help for this, as communicating over GitHub over an issue like this is comparatively slow and not ideal.
